name: Keithblues
favicon: null
layout_spectrum: 0.9262996674515307
typography_spectrum: 0.3808511
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: 'Keith Blues, Creative Direction | Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6339205703698099
  lightness: 0.4781876045744866
  saturation: 0.9586385497823358
  rhythmicContrast: 0.2418642197735608
purpose: []
