name: Keithblues
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50237
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: 'Keith Blues, Creative Direction | Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbdde0'
    - '#05060a'
    - '#83b4c0'
    - '#10313d'
    - '#8b734e'
  brandStrength: 0.8125
  lightness: 0.4781876045744866
  saturation: 0.9586385497823358
  rhythmicContrast: 0.2418642197735608
purpose: []
